import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import axiosInstance from "../Interceptors/axiosInstance";
import Logout from "./Logout.jsx";
import CreateTeam from "./createteam.jsx";
import JoinTeam from "./jointeam.jsx";

{/* Author Name: Pranav Singh */}
function Home() {
  {/* Using useState for handling the user details, and activeTab for 
    conditionally rendering the user details */}
  const [user, setUser] = useState(null);
  const [activeTab, setActiveTab] = useState("create");
  const navigate = useNavigate();

  {/* Using token based authentication that renders the home page if the user is valid based on the
    access token generated by the backend api and then continuously refreshing the token as it expires,
    otherwise navigating the user back to the login page  */}
  useEffect(() => {
    const token = localStorage.getItem("access_token");

    if (!token) {
      navigate("/");
    } else {
      (async () => {
        try {
          const { data } = await axiosInstance.get("accounts/home/");
          setUser(data);
          console.log(data);
        } catch (error) {
          console.log("Not Authorized");
        }
      })();
    }
  }, [navigate]);

  return (
    <div className="h-screen flex bg-gray-100">
      {/* Sidebar */}
      <div className="w-64 bg-white shadow-lg flex flex-col">
        <h2 className="text-2xl font-bold text-center py-6 border-b">PROJECTO</h2>
        <nav className="flex-1 px-4 py-6 space-y-3">
          <button
            onClick={() => setActiveTab("create")}
            className={`w-full text-left px-4 py-2 rounded-lg font-medium transition ${
              activeTab === "create"
                ? "bg-blue-500 text-white shadow-md"
                : "hover:bg-gray-200 text-gray-700"
            }`}
          >
            Create a Team
          </button>
          <button
            onClick={() => setActiveTab("join")}
            className={`w-full text-left px-4 py-2 rounded-lg font-medium transition ${
              activeTab === "join"
                ? "bg-blue-500 text-white shadow-md"
                : "hover:bg-gray-200 text-gray-700"
            }`}
          >
            Join a Team
          </button>
        </nav>

        <div className="border-t p-4">
          <Logout />
        </div>
      </div>

      <div className="flex-1 p-8">
        {/* Conditionally rendering the user details */}

        {user && (
          <div className="flex justify-end mb-6">
            <div className="bg-white shadow-md rounded-xl p-4 w-72 text-sm">

            
              <h3 className="font-semibold text-lg mb-2 text-gray-800">
                {user.firstname} {user.lastname}
              </h3>
              <p className="text-gray-600">Email: {user.email}</p>
              {user.frontend === true &&
                <p className="text-gray-600">Frontend</p> 
              }
              {user.backend === true &&
                <p className="text-gray-600">Backend{user.backend}</p>
              }
            </div>
          </div>
        )}

        {/* Active Tab Content */}
        {activeTab === "create" && <CreateTeam />}
        {activeTab === "join" && <JoinTeam />}
      </div>
    </div>
  );
}

export default Home;
